### ISSUE TITLE
torchvision 0.11 for cp36 and torch 1.11?

### ISSUE THREAD

**Issue by adumont** [Qengineering/PyTorch-Jetson-Nano#4]
NVIDIA provides only Torch 1.11.0 for Jetpack 4.6.1 (Python 3.6) for the Jetson Nano (https://developer.download.nvidia.com/compute/redist/jp/v461/pytorch/torch-1.11.0a0+17540c5+nv22.01-cp36-cp36m-linux_aarch64.whl). I haven't found the corresponding Torchvision.

If I install your Torch 1.10 it won't import (it complains of missing libmpi_cxx.so).

If I intend to install your Torchvision 0.11 (torchvision-0.11.0a0), it removes the nvidia torch 1.11....

I haven't found any working combination... 

Would you build the Torchvision 0.11 for nvidia Torch 1.11.0 ?

**Comment by Qengineering** [comment]
@adumont,

To be honest, I'm not very excited about making this wheel.

The Pytorch team clearly states that version 1.11 only works with Python 3.7. That NVIDIA manages to get it to work with version 3.6 means they probably changed some underlying code. This can turn into a very time consuming adventure for me. The ultimate result can be an avalanche of issues because everyone is of course using that part of PyTorch that doesn't work properly.

libmpi_cxx can be found in `/usr/lib/aarch64-linux-gnu` or in `/usr/lib/aarch64-linux-gnu/openmpi/lib`
`$ find /usr/lib -name libmpi_cxx.*`
